jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false #does not return the whitelabel error page, instead it lets the servlet handle the exception
                     #which returns a simpler 404 error page


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #change this to your database url **supportportal
    password: password #change this to your database username **letmein
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # drops tables and creates new on restart
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #stops Spring from returning Whitelabel Error Page //one way of doing it
  #you need to create an exception handler to handle NoHandlerFoundException.class
#  mvc:
#    throw-exception-if-no-handler-found: true #throws exception if no handler is found instead of handling itself
#  resources:
#    add-mappings: false #do not create a mapping for unknown paths